CREATE TABLE IF NOT EXISTS UTILISATEUR (
  id INT AUTO_INCREMENT PRIMARY KEY,
  identifiant VARCHAR(50) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(255) NOT NULL,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  role VARCHAR(30) NOT NULL,
  matricule_juriste VARCHAR(15) NULL
);
